title:            Aaron Zollman
description:      Aaron Zollman
# Your site's domain goes here. Leave localhost server or blank when working locally.
url:              
disqus_shortname: 

# Owner/author information
owner:
  name:           Aaron Zollman
  avatar:         bio-photo.jpg
  bio:            Security software business guy and hipster-nerd cliche
  email:          az+site@sigsegv.com
  # Social networking links are used in author-bio sidebar. Update and remove as you like.
  twitter:        aaronzollman
  facebook:       
  github:         zollman
  stackoverflow:  
  linkedin:       zollman
  instagram:      
  lastfm:         
  tumblr: 
  pinterest: 
  foursquare: 
  steam: 
  dribbble: 
  # For Google Authorship https://plus.google.com/authorship
  google_plus:    https://plus.google.com/+AaronZollman

# Analytics and webmaster tools stuff goes here
google_analytics:   
google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:        

# Links to include in top navigation
# For external links add external: true
links:
  - title: Whoami
    url: /about/
  - title: Projects
    url: /projects/
  - title: Notes
    url: /posts/

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/New_York
future:      true
pygments:    true
markdown:    kramdown

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers: 
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
