name: Deploy to Staging

on:
  # Trigger on pushes to develop branch
#  push:
#    branches: [develop]
  # Allow manual trigger
  workflow_dispatch:

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    environment: staging # This sets the GitHub environment
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
      - name: Install, build, and upload your site output
        uses: withastro/action@v4
        env:
          PUBLIC_WEBSITE_URL: https://dev.sigsegv.com
          PUBLIC_BASE_PATH: ""

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: https://dev.sigsegv.com
    steps:
      - name: Deploy to Staging
        id: deployment
        uses: actions/deploy-pages@v4
